### ISSUE TITLE
Electron-Phonon coupling

### ISSUE THREAD

**Issue by gtirimbo** [votca/PyVOTCA#14]
According to this [paper](https://hal.archives-ouvertes.fr/hal-00730389/PDF/review_organic.pdf), the electron-phonon coupling can be computed using 

- Ground state normal modes
- Energy levels gradient (KS, GW or BSE) 

Since we can get the normal modes out of ORCA and the gradients can be done numerically we can add this to the repo.

**Comment by felipeZ** [comment]
solved via #24
