### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by junghans** [votca/PyVOTCA#17]
These scripts only interact with xtp and not the other modules so far, so PyVOTCA might be a bit of a too generic name.

**Comment by baumeier** [comment]
Do you anticipate that anyone might be interested in interaction with other modules? Then we could keep it generic for future purposes. Otherwise we make this PyXTP or something.

**Comment by junghans** [comment]
It's on the list for a decade (see https://github.com/votca/csg/issues/43) ;-)

PyXTP seem a bit too specific as well.

Maybe having a PyVOTCA.xtp subclass? Which would leave some space to add `PyVOTCA.tools` and `PyVOTCA.csg` later.

**Comment by baumeier** [comment]
Well, the wrapper.py is actually providing a class called XTP and I am
using it as

From PyVOTCA import xtp

We can rename wrapper.py to xtp.py for clarity.

**Comment by baumeier** [comment]
Fixed by #20
