### ISSUE TITLE
BUG: visualizion plot_absorption_gaussian

### ISSUE THREAD

**Issue by felipeZ** [votca/PyVOTCA#21]
## Problem
in the `plot_absorption_gaussian` the `energy` variable type is float but is used as an int

**Comment by baumeier** [comment]
@felipeZ  Where do you see that?

**Comment by felipeZ** [comment]
see: https://github.com/votca/PyVOTCA/blob/master/pyvotca/visualization.py#L26

the `get_oscillator_strengths` method return a tuple with a float and a Numpy array

**Comment by baumeier** [comment]
Yeah. And where is it used as an `int`? I may be a little stupid here...

**Comment by felipeZ** [comment]
In this other line: https://github.com/votca/PyVOTCA/blob/master/pyvotca/visualization.py#L35

**Comment by baumeier** [comment]
but `energy` is also an array of floats

**Comment by felipeZ** [comment]
then I misunderstood the type

**Comment by baumeier** [comment]
So we are good? :)

**Comment by felipeZ** [comment]
We have to change the types of the `get_oscillator_strengths` methods because it should return a tuple of array and now it return a tuple of [float, array]

**Comment by baumeier** [comment]
If you say so :)
